"""update IsActive

Revision ID: 3643a8308bc1
Revises: 8b3288cc03b8
Create Date: 2026-08-02 22:39:49.903377

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3643a8308bc1'
down_revision: str | Sequence[str] | None = '8b3288cc03b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_active')
    # ### end Alembic commands ###
