"""Add log table

Revision ID: 50f29eacc9c6
Revises: 69279e1d0fb7
Create Date: 2026-07-23 00:28:43.988102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f29eacc9c6'
down_revision: Union[str, Sequence[str], None] = '69279e1d0fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountId', sa.Integer(), nullable=False),
    sa.Column('actionType', sa.Enum('TRANSACTION_CREATED', 'TRANSACTION_FAILED', 'LOGIN_FAILED', name='actiontype'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ipAddress', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['accountId'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
