"""Change accountname to name

Revision ID: 69279e1d0fb7
Revises: 5dfa515f12f5
Create Date: 2026-07-22 23:08:43.104476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69279e1d0fb7'
down_revision: Union[str, Sequence[str], None] = '5dfa515f12f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('account', 'accountName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('accountName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('account', 'name')
    # ### end Alembic commands ###
