"""edit task2

Revision ID: 8e38a0333785
Revises: 967592c323f0
Create Date: 2026-09-17 16:50:03.766512

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e38a0333785'
down_revision: str | Sequence[str] | None = '967592c323f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_finish', sa.Boolean(), nullable=False))
    op.add_column('task', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('task', 'IsActive')
    op.drop_column('task', 'isFinish')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('isFinish', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('IsActive', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('task', 'is_active')
    op.drop_column('task', 'is_finish')
    # ### end Alembic commands ###
