"""edit task

Revision ID: 967592c323f0
Revises: 8ccb0f22c7c8
Create Date: 2026-09-17 15:30:02.255453

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '967592c323f0'
down_revision: str | Sequence[str] | None = '8ccb0f22c7c8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('title', sa.String(), nullable=True))
    op.add_column('task', sa.Column('IsActive', sa.Boolean(), nullable=False))
    op.drop_column('task', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'IsActive')
    op.drop_column('task', 'title')
    # ### end Alembic commands ###
